const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state = {page:'home', data:null, history:[], apps:[], range:60, socket:null, retry:0, paired:false, stale:true};
const pages = {home:['Command center','Your laptop. Everything in view.'], gaming:['Gaming station','Stay in the game. Keep an eye on everything else.'], hardware:['Hardware monitor','A closer look at the machine behind the screen.'], graphs:['Live graphs','The full picture, one sample at a time.'], apps:['Applications','Your everyday apps. One touch away.'], system:['System & connection','Your laptop and your command surface. Connected.']};
let reconnectTimer, toastTimer, lastSample = 0;
const format = (v, digits=0) => v == null ? '—' : Number(v).toLocaleString(undefined,{maximumFractionDigits:digits});
const gb = v => v == null ? '—' : format(v / 1024 ** 3,1);
const mb = v => v == null ? '—' : format(v / 1024 ** 2,1);
const path = (obj, key) => key.split('.').reduce((v,k) => v?.[k],obj);
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4000)}
async function api(url, options={}){
  const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers}});
  if(response.status===401){showPairing();throw new Error('Pair this device to continue.')}
  const body=await response.json();
  if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:'Please check the input and try again.');
  return body;
}
function showPairing(){state.paired=false;clearTimeout(reconnectTimer);state.socket?.close();if(!$('#pair-dialog').open)$('#pair-dialog').showModal();setConnection(false,'PAIR DEVICE')}
function setConnection(connected,label){state.stale=!connected;document.body.classList.toggle('stale',!connected);$('#connection').textContent=`● ${label}`;$('#connection').classList.toggle('offline',!connected);$('#offline-banner').hidden=connected||!state.paired}
function metric(label,key,unit,accent,note){return `<article class="card accent-${accent}"><div class="card-top"><span class="label">${label}</span><span class="chip" data-note="${note}">LIVE</span></div><div class="value"><span data-metric="${key}">—</span><em>${unit}</em></div><div class="sub-value" data-sub="${key}">Waiting for sensor</div><svg class="spark" data-spark="${key}" viewBox="0 0 240 48" preserveAspectRatio="none" aria-label="${label} recent trend"></svg></article>`}
function metrics(){return `<div class="grid metrics-grid">${metric('CPU LOAD','cpu.usage','%','green','cpu')}${metric('GPU LOAD','gpu.usage','%','cyan','gpu')}${metric('MEMORY','memory.percent','%','purple','memory')}${metric('GPU TEMPERATURE','gpu.temperature','°C','orange','temperature')}</div>`}
function rangeButtons(){return `<div class="range-control" aria-label="Graph history range">${[[30,'30s'],[60,'1m'],[300,'5m'],[900,'15m'],[3600,'1h']].map(([s,l])=>`<button data-range="${s}" class="${state.range===s?'active':''}">${l}</button>`).join('')}</div>`}
function graphCard(title='Performance timeline',keys='cpu.usage,gpu.usage',max=100){return `<article class="card"><div class="card-top"><h2 class="section-title">${title}</h2>${rangeButtons()}</div><div class="section-note">${max===100?'Utilization · percent':'Sensor history · native units'} / ${state.range>=60?state.range/60+' minutes':state.range+' seconds'}</div><div class="legend"><span><i class="cpu-dot"></i>CPU</span><span><i class="gpu-dot"></i>GPU</span></div><svg class="chart" data-chart="${keys}" data-max="${max}" viewBox="0 0 600 156" preserveAspectRatio="none" role="img" aria-label="${title}"></svg><div class="chart-labels"><span data-history-label>Collecting history</span><span>NOW</span></div></article>`}
function resource(name,key,color){return `<div class="resource accent-${color}"><div class="resource-title"><span>${name}</span><strong data-resource="${key}">—</strong></div><div class="track"><i data-bar="${key}"></i></div><div class="resource-note" data-resource-note="${key}">Waiting for data</div></div>`}
function resources(){return `<article class="card"><div class="card-top"><h2 class="section-title">System resources</h2><span class="chip">CAPACITY</span></div>${resource('Memory','memory','purple')}${resource('Graphics memory','gpu','cyan')}${resource('System drive','storage','orange')}<div class="control-note"><span class="online-dot"></span><span data-battery>Battery unavailable</span></div></article>`}
function appTiles(all=false){return `<div class="apps-grid">${state.apps.slice(0,all?100:8).map(app=>`<button class="app-tile" data-app="${escapeHtml(app.id)}" ${!app.available?'disabled':''}><span class="app-icon">${escapeHtml(app.icon)}</span><span>${escapeHtml(app.name)}</span><small class="app-status ${app.running?'running':''}">${app.running?'● Running':!app.available?'Not installed':'Launch app'}</small></button>`).join('')}</div>`}
function media(){return `<article class="card"><div class="card-top"><h2 class="section-title">Quick controls</h2><span class="chip">WINDOWS</span></div><div class="controls">${[['previous','⏮','Previous'],['play-pause','⏯','Play / pause'],['next','⏭','Next'],['volume-down','−','Volume down'],['mute','◖','Mute'],['volume-up','+','Volume up']].map(([id,symbol,label])=>`<button data-media="${id}" aria-label="${label}">${symbol}<small>${label}</small></button>`).join('')}</div><div class="control-note">Controls the laptop’s active media session.</div></article>`}
function row(label,key){return `<div class="detail-row"><span>${label}</span><strong data-detail="${key}">—</strong></div>`}
function render(){
  const [title,description]=pages[state.page];$('#page-title').innerHTML=`${title}<span>.</span>`;$('#page-description').textContent=description;
  let content='';
  if(state.page==='home')content=`${metrics()}<div class="grid middle-grid">${graphCard()}${resources()}</div><div class="grid bottom-grid"><article class="card"><div class="card-top"><h2 class="section-title">Quick launch</h2><span class="chip">YOUR WORKSPACE</span></div>${appTiles()}</article>${media()}</div>`;
  if(state.page==='gaming')content=`${metrics()}<div class="grid middle-grid">${graphCard()}${resources()}</div><article class="card notice integration-note">FPS, frame time, CPU temperatures, and fans need RTSS / HWiNFO integrations. These readings are not available in this foundation build.</article>`;
  if(state.page==='hardware')content=`<div class="grid detail-grid"><article class="card"><h2 class="section-title">Processor</h2>${row('Utilization','cpu.usage')}${row('Reported clock','cpu.clock')}${row('Logical processors','system.logical_cores')}${row('Package temperature','cpu.temperature')}<div id="cores" class="core-grid"></div></article><article class="card"><h2 class="section-title">Graphics</h2>${row('Graphics adapter','gpu.name')}${row('Utilization','gpu.usage')}${row('Temperature','gpu.temperature')}${row('Core clock','gpu.clock')}${row('Board power','gpu.power')}${row('Sensor source','gpu.source')}</article>${resources()}<article class="card"><h2 class="section-title">Storage & network</h2>${row('Disk read','storage.read')}${row('Disk write','storage.write')}${row('Download','network.download')}${row('Upload','network.upload')}<div id="drives"></div></article></div>`;
  if(state.page==='graphs')content=`<div class="grid detail-grid">${graphCard()}${graphCard('GPU temperature','gpu.temperature',100)}${graphCard('Memory utilization','memory.percent',100)}${graphCard('Network throughput · MB/s','network.download,network.upload',0)}</div>`;
  if(state.page==='apps')content=`<article class="card"><div class="card-top"><h2 class="section-title">Application library</h2><span class="chip">REGISTERED ON YOUR LAPTOP</span></div><p class="section-note">Add apps in config/apps.local.json on your laptop. Uninstalled executables are disabled; URI handlers are checked at launch.</p>${appTiles(true)}</article>`;
  if(state.page==='system')content=`<div class="grid detail-grid"><article class="card"><h2 class="section-title">Your laptop</h2>${row('Computer','system.hostname')}${row('Operating system','system.os')}${row('Uptime','system.uptime')}${row('Battery','battery.percent')}${row('Power connection','battery.charging')}<div id="addresses"></div></article>${media()}<article class="card"><h2 class="section-title">Integrations</h2>${row('Windows telemetry','integrations.windows')}${row('NVIDIA sensors','integrations.nvidia')}${row('HWiNFO sensors','integrations.hwinfo')}${row('FPS / RTSS','integrations.rtss')}${row('OBS Studio','integrations.obs')}</article><article class="card"><h2 class="section-title">Tablet settings</h2><p class="section-note">Fullscreen works over Wi-Fi. Keep-awake requires HTTPS and browser support. Sessions last 12 hours.</p><div class="page-actions"><button id="wake-lock">Keep screen awake</button><button id="disconnect">Unpair device</button></div><p class="section-note">Sleep, restart, shutdown, microphone control, OBS, games, and macros will be added in subsequent milestones.</p></article></div>`;
  $('#page-content').innerHTML=content;
  document.querySelectorAll('.nav').forEach(n=>{n.classList.toggle('active',n.dataset.page===state.page);n.setAttribute('aria-current',n.dataset.page===state.page?'page':'false')});
  document.querySelectorAll('.cpu-dot').forEach(el=>el.style.background='#bbf780');document.querySelectorAll('.gpu-dot').forEach(el=>el.style.background='#76dbe7');
  document.querySelectorAll('[data-app]').forEach(el=>{const app=state.apps.find(a=>a.id===el.dataset.app);el.style.setProperty('--icon',app.color)});
  update();
}
function display(key,v){if(v==null)return 'Unavailable';if(key==='system.uptime')return `${format(v/3600,1)} hours`;if(key==='battery.charging')return v?'AC connected':'On battery';if(/network\.|storage\.(read|write)/.test(key))return `${mb(v)} MB/s`;if(/\.usage$|battery.percent/.test(key))return `${format(v)} %`;if(/\.temperature$/.test(key))return `${format(v)} °C`;if(/\.clock$/.test(key))return `${format(v)} MHz`;if(/\.power$/.test(key))return `${format(v)} W`;return String(v)}
function series(key){const cutoff=Date.now()-state.range*1000;return state.history.filter(s=>Date.parse(s.timestamp)>=cutoff).map(s=>({time:Date.parse(s.timestamp),value:path(s,key)}))}
function line(points,width,height,max){const start=Date.now()-state.range*1000;let pen=false;return points.map(p=>{if(p.value==null){pen=false;return ''}const x=Math.max(0,Math.min(width,(p.time-start)/(state.range*1000)*width));const y=height-Math.max(0,Math.min(1,p.value/max))*(height-8)-4;const command=pen?'L':'M';pen=true;return `${command}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')}
function charts(){document.querySelectorAll('[data-spark]').forEach(el=>{const points=series(el.dataset.spark);const d=line(points,240,48,100);el.innerHTML=`<path d="${d}" fill="none" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke"/>`});document.querySelectorAll('[data-chart]').forEach(el=>{const keys=el.dataset.chart.split(',');const points=keys.map(series);let max=Number(el.dataset.max);if(!max)max=Math.max(1,...points.flat().map(p=>(p.value??0)/1024**2))*1.1;el.innerHTML=[25,75,125].map(y=>`<line x1="0" x2="600" y1="${y}" y2="${y}" class="chart-grid"/>`).join('')+points.map((values,i)=>`<path d="${line(keys[i].startsWith('network.')?values.map(p=>({...p,value:p.value==null?null:p.value/1024**2})):values,600,156,max)}" fill="none" stroke="${['#bbf780','#76dbe7'][i]}" stroke-width="2" vector-effect="non-scaling-stroke"/>`).join('');const legend=el.parentElement.querySelector('.legend');legend.innerHTML=keys.map((key,i)=>`<span>${escapeHtml(key.replace('.', ' · '))}</span>`).join('');legend.querySelectorAll('span').forEach((s,i)=>s.style.color=['#bbf780','#76dbe7'][i])});document.querySelectorAll('[data-history-label]').forEach(el=>el.textContent=state.history.length?`${Math.min(state.range,Math.max(0,Math.round((Date.now()-Date.parse(state.history[0].timestamp))/1000)))}s of history available`:'Collecting history')}
function update(){
  const d=state.data;if(!d){charts();return}
  $('#hostname').textContent=d.system.hostname.toUpperCase();$('#system-summary').textContent=`${d.system.logical_cores} threads · ${gb(d.memory.total)} GB RAM${d.gpu?' · '+d.gpu.name:''}`;$('#footer-ip').textContent=location.host+' / PAIRED';
  document.querySelectorAll('[data-metric]').forEach(el=>el.textContent=format(path(d,el.dataset.metric)));
  document.querySelectorAll('[data-note]').forEach(el=>el.textContent=el.dataset.note==='gpu'||el.dataset.note==='temperature'?(d.gpu?'NVIDIA':'NO SENSOR'):'WINDOWS');
  const subtitles={'cpu.usage':d.cpu.clock?`${format(d.cpu.clock/1000,2)} GHz · ${d.system.logical_cores} logical processors`:'Live processor utilization','gpu.usage':d.gpu?d.gpu.name:'NVIDIA sensor unavailable','memory.percent':`${gb(d.memory.used)} / ${gb(d.memory.total)} GB in use`,'gpu.temperature':d.gpu?'Sensor source: NVIDIA':'Detailed sensors not connected'};
  document.querySelectorAll('[data-sub]').forEach(el=>el.textContent=subtitles[el.dataset.sub]);
  document.querySelectorAll('[data-detail]').forEach(el=>el.textContent=display(el.dataset.detail,path(d,el.dataset.detail)));
  const resources={memory:[d.memory.percent,`${gb(d.memory.used)} / ${gb(d.memory.total)} GB`,`${gb(d.memory.total-d.memory.used)} GB available`],gpu:[d.gpu?.memory_total?100*d.gpu.memory_used/d.gpu.memory_total:0,d.gpu?`${format(d.gpu.memory_used/1024,1)} / ${format(d.gpu.memory_total/1024,1)} GB`:'Unavailable','Dedicated graphics memory'],storage:[d.storage.drives[0]?.percent??0,d.storage.drives[0]?`${gb(d.storage.drives[0].used)} / ${gb(d.storage.drives[0].total)} GB`:'Unavailable',d.storage.drives[0]?`${gb(d.storage.drives[0].free)} GB free`:'No drive reported']};
  document.querySelectorAll('[data-resource]').forEach(el=>el.textContent=resources[el.dataset.resource][1]);document.querySelectorAll('[data-bar]').forEach(el=>el.style.width=`${Math.min(100,resources[el.dataset.bar][0])}%`);document.querySelectorAll('[data-resource-note]').forEach(el=>el.textContent=resources[el.dataset.resourceNote][2]);
  document.querySelectorAll('[data-battery]').forEach(el=>el.textContent=d.battery?`${format(d.battery.percent)}% battery · ${d.battery.charging?'AC connected':'On battery'}`:'No battery reported');
  if($('#cores'))$('#cores').innerHTML=d.cpu.cores.map((v,i)=>`<div class="core"><small>CPU ${i+1}</small>${format(v)}%</div>`).join('');
  if($('#drives'))$('#drives').innerHTML=d.storage.drives.map(drive=>`<div class="detail-row"><span>${escapeHtml(drive.name)}</span><strong>${gb(drive.free)} GB free</strong></div>`).join('');
  if($('#addresses'))$('#addresses').innerHTML=d.network.addresses.map(a=>`<div class="detail-row"><span>${escapeHtml(a.adapter)}</span><strong>${escapeHtml(a.ip)}</strong></div>`).join('');
  charts();
}
async function refreshHistory(){const range=state.range;try{const body=await api(`/api/history?seconds=${range}`);if(range!==state.range)return;const byTime=new Map([...body.samples,...state.history].map(s=>[s.timestamp,s]));state.history=[...byTime.values()].sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)).slice(-3600);charts()}catch(e){if(state.paired)toast(e.message)}}
async function refreshApps(){try{state.apps=await api('/api/apps');if(!document.querySelector('[data-app]')&&(state.page==='home'||state.page==='apps'))render();else document.querySelectorAll('[data-app]').forEach(el=>{const app=state.apps.find(a=>a.id===el.dataset.app);if(!app)return;el.disabled=!app.available;const label=el.querySelector('.app-status');label.textContent=app.running?'● Running':!app.available?'Not installed':'Launch app';label.classList.toggle('running',app.running)})}catch(e){if(state.paired)toast(e.message)}}
function connect(){
  clearTimeout(reconnectTimer);if(!state.paired)return;
  const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);state.socket=ws;
  ws.onopen=()=>{state.retry=0;refreshHistory();refreshApps()};
  ws.onmessage=event=>{const packet=JSON.parse(event.data);if(!packet.data){setConnection(false,'WAITING FOR SENSOR');return}state.data=packet.data;lastSample=Date.parse(packet.data.timestamp);if(state.history.at(-1)?.timestamp!==packet.data.timestamp)state.history.push(packet.data);state.history=state.history.filter(s=>Date.parse(s.timestamp)>Date.now()-3600000).slice(-3600);const fresh=Date.now()-lastSample<=5000;setConnection(fresh,fresh?'LIVE CONNECTION':'READINGS STALE');update()};
  ws.onclose=event=>{if(ws!==state.socket)return;setConnection(false,'RECONNECTING');if(event.code===1008){showPairing();return}if(state.paired)reconnectTimer=setTimeout(connect,Math.min(10000,1000*2**state.retry++)+Math.random()*500)};
  ws.onerror=()=>ws.close();
}
document.querySelector('nav').addEventListener('click',event=>{const button=event.target.closest('[data-page]');if(!button)return;state.page=button.dataset.page;location.hash=state.page;render()});
$('#page-content').addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{
  if(button.dataset.app){button.disabled=true;try{const result=await api('/api/apps/launch',{method:'POST',body:JSON.stringify({id:button.dataset.app})});toast(result.message);setTimeout(refreshApps,1500)}finally{button.disabled=false}}
  if(button.dataset.media){const result=await api(`/api/media/${button.dataset.media}`,{method:'POST'});toast(result.message)}
  if(button.dataset.range){state.range=Number(button.dataset.range);render();await refreshHistory()}
  if(button.id==='disconnect'){await api('/api/logout',{method:'POST'});state.data=null;state.history=[];render();showPairing()}
  if(button.id==='wake-lock'){if(!('wakeLock' in navigator))throw new Error('Keep-awake requires HTTPS and browser support.');await requestWakeLock();toast('Screen will stay awake while this page is visible.')}
}catch(e){toast(e.message)}});
let wakeLock,keepAwake=false;
async function requestWakeLock(){wakeLock=await navigator.wakeLock.request('screen');keepAwake=true}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){if(keepAwake)requestWakeLock().catch(()=>{});if(state.paired&&state.socket?.readyState!==WebSocket.OPEN)connect()}});
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('Fullscreen is unavailable in this browser.')}});
$('#pair-dialog').addEventListener('cancel',e=>e.preventDefault());
$('#pair-form').addEventListener('submit',async event=>{event.preventDefault();const button=$('#pair-form button');button.disabled=true;$('#pair-error').textContent='';try{await api('/api/pair',{method:'POST',body:JSON.stringify({code:$('#pair-code').value.trim().toUpperCase()})});$('#pair-code').value='';$('#pair-dialog').close();state.paired=true;await refreshApps();render();connect()}catch(e){$('#pair-error').textContent=e.message}finally{button.disabled=false}});
let swipeStart;
$('#page-content').addEventListener('touchstart',e=>{if(e.target.closest('button,input,select'))return;swipeStart=[e.changedTouches[0].clientX,e.changedTouches[0].clientY]},{passive:true});
$('#page-content').addEventListener('touchend',e=>{if(!swipeStart)return;const dx=e.changedTouches[0].clientX-swipeStart[0],dy=e.changedTouches[0].clientY-swipeStart[1];swipeStart=null;if(Math.abs(dx)>120&&Math.abs(dy)<60){const ids=Object.keys(pages);state.page=ids[(ids.indexOf(state.page)+(dx<0?1:-1)+ids.length)%ids.length];location.hash=state.page;render()}},{passive:true});
setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false});if(lastSample&&Date.now()-lastSample>5000&&state.paired)setConnection(false,'READINGS STALE')},1000);
setInterval(()=>{if(state.paired&&document.visibilityState==='visible')refreshApps()},15000);
async function init(){if(pages[location.hash.slice(1)])state.page=location.hash.slice(1);render();try{state.data=await api('/api/system');state.paired=true;await refreshApps();render();connect()}catch(e){if(e.message==='Waiting for a hardware sample.'){state.paired=true;connect()}else showPairing()}}
init();
