const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state = {page:'home', data:null, history:[], apps:[], games:[], gameLibrary:null, gameFilter:'all',gameSearch:'',range:60, socket:null, retry:0, paired:false, stale:true, auth:null};
const pages = {home:['Command center','Your laptop. Everything in view.'], gaming:['Gaming station','Stay in the game. Keep an eye on everything else.'], games:['Game library','Your installed games. Ready when you are.'],hardware:['Hardware monitor','A closer look at the machine behind the screen.'], graphs:['Live graphs','The full picture, one sample at a time.'], apps:['Applications','Your everyday apps. One touch away.'], clock:['Time station','A quieter view of your day.'],ambient:['Ambient collection','Turn your command surface into a little piece of art.'],system:['System & connection','Your laptop and your command surface. Connected.'], devices:['Device access','Approve your browsers. Keep your laptop private.']};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=glyph(el.dataset.icon));
let reconnectTimer, toastTimer, lastSample = 0;
const format = (v, digits=0) => v == null ? '—' : Number(v).toLocaleString(undefined,{maximumFractionDigits:digits});
const gb = v => v == null ? '—' : format(v / 1024 ** 3,1);
const mb = v => v == null ? '—' : format(v / 1024 ** 2,1);
const path = (obj, key) => key.split('.').reduce((v,k) => v?.[k],obj);
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4000)}
async function api(url, options={}){
  const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers}});
  const body=await response.json();
  if(response.status===401&&!['/api/pair','/api/device/request'].includes(url)){showPairing();throw new Error(typeof body.detail==='string'?body.detail:'This browser needs laptop approval.')}
  if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:'Please check the input and try again.');
  return body;
}
function showPairing(){state.paired=false;clearTimeout(reconnectTimer);state.socket?.close();if(!$('#pair-dialog').open)$('#pair-dialog').showModal();syncScreenAwake();updateSurfaceBackground();updateAmbient();setConnection(false,'APPROVAL REQUIRED');loadPairingMode()}
function setConnection(connected,label){state.stale=!connected;document.body.classList.toggle('stale',!connected);$('#connection').textContent=`● ${label}`;$('#connection').classList.toggle('offline',!connected);$('#offline-banner').hidden=connected||!state.paired}
function metric(label,key,unit,accent,note){return `<article class="card accent-${accent}"><div class="card-top"><span class="label">${label}</span><span class="chip" data-note="${note}">LIVE</span></div><div class="value"><span data-metric="${key}">—</span><em>${unit}</em></div><div class="sub-value" data-sub="${key}">Waiting for sensor</div><svg class="spark" data-spark="${key}" viewBox="0 0 240 48" preserveAspectRatio="none" aria-label="${label} recent trend"></svg></article>`}
function metrics(){return `<div class="grid metrics-grid">${metric('CPU LOAD','cpu.usage','%','green','cpu')}${metric('GPU LOAD','gpu.usage','%','cyan','gpu')}${metric('MEMORY','memory.percent','%','purple','memory')}${metric('GPU TEMPERATURE','gpu.temperature','°C','orange','temperature')}</div>`}
function rangeButtons(){return `<div class="range-control" aria-label="Graph history range">${[[30,'30s'],[60,'1m'],[300,'5m'],[900,'15m'],[3600,'1h']].map(([s,l])=>`<button data-range="${s}" class="${state.range===s?'active':''}">${l}</button>`).join('')}</div>`}
function graphCard(title='Performance timeline',keys='cpu.usage,gpu.usage',max=100){return `<article class="card"><div class="card-top"><h2 class="section-title">${title}</h2>${rangeButtons()}</div><div class="section-note">${max===100?'Utilization · percent':'Sensor history · native units'} / ${state.range>=60?state.range/60+' minutes':state.range+' seconds'}</div><div class="legend"><span><i class="cpu-dot"></i>CPU</span><span><i class="gpu-dot"></i>GPU</span></div><svg class="chart" data-chart="${keys}" data-max="${max}" viewBox="0 0 600 156" preserveAspectRatio="none" role="img" aria-label="${title}"></svg><div class="chart-labels"><span data-history-label>Collecting history</span><span>NOW</span></div></article>`}
function resource(name,key,color){return `<div class="resource accent-${color}"><div class="resource-title"><span>${name}</span><strong data-resource="${key}">—</strong></div><div class="track"><i data-bar="${key}"></i></div><div class="resource-note" data-resource-note="${key}">Waiting for data</div></div>`}
function resources(){return `<article class="card"><div class="card-top"><h2 class="section-title">System resources</h2><span class="chip">CAPACITY</span></div>${resource('Memory','memory','purple')}${resource('Graphics memory','gpu','cyan')}${resource('System drive','storage','orange')}<div class="control-note"><span class="online-dot"></span><span data-battery>Battery unavailable</span></div></article>`}
const brandAssets={steam:'steam',discord:'discord',spotify:'spotify',brave:'brave',youtube:'youtube',obs:'obsstudio'};
function appStatus(app){return !app.available?(app.kind==='website'?'Brave not installed':'Not installed'):app.kind==='website'?'Open in Brave':app.running?'● Running':'Launch app'}
function appTiles(all=false){return `<div class="apps-grid ${all?'app-library':''}">${state.apps.slice(0,all?100:8).map(app=>`<button class="app-tile" data-app="${escapeHtml(app.id)}" ${!app.available?'disabled':''}><span class="app-icon">${brandAssets[app.id]?`<img src="/static/assets/icons/${brandAssets[app.id]}.svg" alt="" width="30" height="30">`:glyph(app.id)}</span><span class="app-name">${escapeHtml(app.name)}</span><small class="app-status ${app.running&&app.kind!=='website'?'running':''}">${appStatus(app)}</small><span class="app-arrow">${glyph('arrow')}</span></button>`).join('')}</div>`}
function media(){return `<article class="card"><div class="card-top"><h2 class="section-title">Quick controls</h2><span class="chip">MEDIA</span></div><div class="controls">${[['previous','previous','Previous'],['play-pause','play','Play / pause'],['next','next','Next'],['volume-down','minus','Volume down'],['mute','mute','Mute'],['volume-up','plus','Volume up']].map(([id,icon,label])=>`<button data-media="${id}" aria-label="${label}">${glyph(icon)}<small>${label}</small></button>`).join('')}</div><div class="control-note">Your sound. Right here.</div></article>`}
function surfaceVital(label,key,unit){return `<div class="surface-vital"><span>${label}</span><strong><b data-metric="${key}">—</b><em>${unit}</em></strong></div>`}
function homeSound(){const buttons=items=>items.map(([id,icon,label])=>`<button data-media="${id}" aria-label="${label}" title="${label}">${glyph(icon)}</button>`).join('');return `<div class="home-media orbit-controls"><div class="orbit-playback" role="group" aria-label="Playback controls">${buttons([['previous','previous','Previous track'],['play-pause','play','Play or pause'],['next','next','Next track']])}</div><div class="orbit-volume" role="group" aria-label="Laptop volume">${buttons([['volume-down','minus','Volume down'],['mute','mute','Mute or unmute'],['volume-up','plus','Volume up']])}</div></div>`}
function surfaceHome(){return `<div class="home-surface orbit-home"><section class="orbit-stage"><div class="orbit-intro"><span class="surface-overline">YOUR PERSONAL ORBIT</span><h2>Everything,<br><i>in orbit.</i></h2><p>Your laptop. Within reach.</p></div><button class="surface-link orbit-games" data-go="games">Open game library ${glyph('arrow')}</button><span class="orbit-credit">NASA’s Goddard Space Flight Center / Jeremy Schnittman</span></section><div class="orbit-telemetry"><div class="orbit-cpu"><span class="orbit-label">PROCESSOR / LIVE LOAD</span><div class="orbit-cpu-line"><strong class="orbit-cpu-value"><span data-metric="cpu.usage">—</span><em>%</em></strong><svg class="surface-trace" data-spark="cpu.usage" viewBox="0 0 240 48" preserveAspectRatio="none" aria-label="Live processor load trend"></svg></div><span class="reading-detail" data-sub="cpu.usage">Connecting to your laptop</span></div><div class="surface-vitals">${surfaceVital('GRAPHICS','gpu.usage','%')}${surfaceVital('MEMORY','memory.percent','%')}${surfaceVital('GPU TEMP','gpu.temperature','°')}</div>${homeSound()}</div><div class="home-launch">${appTiles()}<button class="surface-link" data-go="apps">All apps ${glyph('arrow')}</button></div></div>`}
function performanceSurface(){return `<div class="performance-surface"><div class="performance-heading"><span class="surface-overline">FEEL THE MACHINE</span><h2>Ready.<br><i>Set. Play.</i></h2><span class="reading-detail" data-detail="gpu.name">Graphics sensor unavailable</span></div><div class="performance-main"><span class="reading-label">GPU TEMPERATURE</span><div class="thermal-reading"><span data-metric="gpu.temperature">—</span><em>°</em></div><svg class="surface-trace" data-spark="gpu.temperature" viewBox="0 0 240 48" preserveAspectRatio="none" aria-label="Graphics temperature trend"></svg></div><div class="performance-vitals">${surfaceVital('CPU LOAD','cpu.usage','%')}${surfaceVital('GPU LOAD','gpu.usage','%')}${surfaceVital('MEMORY','memory.percent','%')}<div class="surface-vital"><span>FRAME RATE</span><strong>—</strong><small>FPS sensor not connected</small></div></div><button class="surface-link" data-go="graphs">See the performance history ${glyph('arrow')}</button></div>`}
function row(label,key){return `<div class="detail-row"><span>${label}</span><strong data-detail="${key}">—</strong></div>`}
function render(){
  document.body.dataset.view=state.page;
  document.querySelectorAll('#page-content video').forEach(video=>video.pause());
  const [title,description]=pages[state.page];$('#page-title').innerHTML=`${title}<span>.</span>`;$('#page-description').textContent=description;
  let content='';
  if(state.page==='home')content=surfaceHome();
  if(state.page==='gaming')content=performanceSurface();
  if(state.page==='hardware')content=`<div class="grid detail-grid"><article class="card"><h2 class="section-title">Processor</h2>${row('Utilization','cpu.usage')}${row('Reported clock','cpu.clock')}${row('Logical processors','system.logical_cores')}${row('Package temperature','cpu.temperature')}<div id="cores" class="core-grid"></div></article><article class="card"><h2 class="section-title">Graphics</h2>${row('Graphics adapter','gpu.name')}${row('Utilization','gpu.usage')}${row('Temperature','gpu.temperature')}${row('Core clock','gpu.clock')}${row('Board power','gpu.power')}${row('Sensor source','gpu.source')}</article>${resources()}<article class="card"><h2 class="section-title">Storage & network</h2>${row('Disk read','storage.read')}${row('Disk write','storage.write')}${row('Download','network.download')}${row('Upload','network.upload')}<div id="drives"></div></article></div>`;
  if(state.page==='graphs')content=`<div class="grid detail-grid">${graphCard()}${graphCard('GPU temperature','gpu.temperature',100)}${graphCard('Memory utilization','memory.percent',100)}${graphCard('Network throughput · MB/s','network.download,network.upload',0)}</div>`;
  if(state.page==='apps')content=`<div class="apps-surface"><span class="surface-overline">A TOUCH AWAY</span><h2>Open <i>something.</i></h2>${appTiles(true)}<p class="apps-caption">On your laptop. Right where you want it.</p></div>`;
  if(state.page==='games')content=gamesScreen();
  if(state.page==='clock')content=clockScreen();
  if(state.page==='ambient')content=ambientScreen();
  if(state.page==='system')content=`<div class="grid detail-grid"><article class="card"><h2 class="section-title">Your laptop</h2>${row('Computer','system.hostname')}${row('Operating system','system.os')}${row('Uptime','system.uptime')}${row('Battery','battery.percent')}${row('Power connection','battery.charging')}<div id="addresses"></div></article>${media()}<article class="card"><h2 class="section-title">Integrations</h2>${row('Windows telemetry','integrations.windows')}${row('NVIDIA sensors','integrations.nvidia')}${row('HWiNFO sensors','integrations.hwinfo')}${row('FPS / RTSS','integrations.rtss')}${row('OBS Studio','integrations.obs')}</article><article class="card"><h2 class="section-title">Tablet settings</h2>${displaySettings()}${backgroundSettings()}${wakeSettings()}<p class="section-note">Fullscreen works over Wi-Fi. Keep-awake requires HTTPS and browser support. Approved browsers are remembered for up to 180 days.</p><div class="page-actions"><button id="wake-lock">Keep screen awake</button><button id="wake-retry" hidden>Retry keep-awake</button><button id="disconnect">Unpair device</button></div><p class="section-note">Sleep, restart, shutdown, microphone control, OBS, games, and macros will be added in subsequent milestones.</p></article></div>`;
  $('#page-content').innerHTML=content;
  document.querySelectorAll('.nav').forEach(n=>{n.classList.toggle('active',n.dataset.page===state.page);n.setAttribute('aria-current',n.dataset.page===state.page?'page':'false')});
  $('#more-toggle').classList.toggle('active',['hardware','graphs','system','devices'].includes(state.page));
  document.querySelectorAll('.cpu-dot').forEach(el=>el.style.background='#bbf780');document.querySelectorAll('.gpu-dot').forEach(el=>el.style.background='#76dbe7');
  document.querySelectorAll('[data-app]').forEach(el=>{const app=state.apps.find(a=>a.id===el.dataset.app);el.style.setProperty('--icon',app.color)});
  update();
  mountScreens();
  updateSurfaceBackground();
  paintScreenAwake();
  if(state.page==='system'||state.page==='devices')renderDevices();
}
function display(key,v){if(v==null)return 'Unavailable';if(key==='system.uptime')return `${format(v/3600,1)} hours`;if(key==='battery.charging')return v?'AC connected':'On battery';if(/network\.|storage\.(read|write)/.test(key))return `${mb(v)} MB/s`;if(/\.usage$|battery.percent/.test(key))return `${format(v)} %`;if(/\.temperature$/.test(key))return `${format(v)} °C`;if(/\.clock$/.test(key))return `${format(v)} MHz`;if(/\.power$/.test(key))return `${format(v)} W`;return String(v)}
function series(key){const cutoff=Date.now()-state.range*1000;return state.history.filter(s=>Date.parse(s.timestamp)>=cutoff).map(s=>({time:Date.parse(s.timestamp),value:path(s,key)}))}
function line(points,width,height,max){const start=Date.now()-state.range*1000;let pen=false;return points.map(p=>{if(p.value==null){pen=false;return ''}const x=Math.max(0,Math.min(width,(p.time-start)/(state.range*1000)*width));const y=height-Math.max(0,Math.min(1,p.value/max))*(height-8)-4;const command=pen?'L':'M';pen=true;return `${command}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')}
function charts(){document.querySelectorAll('[data-spark]').forEach(el=>{const points=series(el.dataset.spark);const d=line(points,240,48,100);el.innerHTML=`<path d="${d}" fill="none" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke"/>`});document.querySelectorAll('[data-chart]').forEach(el=>{const keys=el.dataset.chart.split(',');const points=keys.map(series);let max=Number(el.dataset.max);if(!max)max=Math.max(1,...points.flat().map(p=>(p.value??0)/1024**2))*1.1;el.innerHTML=[25,75,125].map(y=>`<line x1="0" x2="600" y1="${y}" y2="${y}" class="chart-grid"/>`).join('')+points.map((values,i)=>`<path d="${line(keys[i].startsWith('network.')?values.map(p=>({...p,value:p.value==null?null:p.value/1024**2})):values,600,156,max)}" fill="none" stroke="${['#bbf780','#76dbe7'][i]}" stroke-width="2" vector-effect="non-scaling-stroke"/>`).join('');const legend=el.parentElement.querySelector('.legend');legend.innerHTML=keys.map((key,i)=>`<span>${escapeHtml(key.replace('.', ' · '))}</span>`).join('');legend.querySelectorAll('span').forEach((s,i)=>s.style.color=['#bbf780','#76dbe7'][i])});document.querySelectorAll('[data-history-label]').forEach(el=>el.textContent=state.history.length?`${Math.min(state.range,Math.max(0,Math.round((Date.now()-Date.parse(state.history[0].timestamp))/1000)))}s of history available`:'Collecting history')}
function update(){
  const d=state.data;if(!d){charts();return}
  $('#hostname').textContent=d.system.hostname.toUpperCase();$('#system-summary').textContent=`${d.system.logical_cores} threads · ${gb(d.memory.total)} GB RAM${d.gpu?' · '+d.gpu.name:''}`;$('#footer-ip').textContent=location.host+' / PAIRED';
  document.querySelectorAll('[data-metric]').forEach(el=>el.textContent=format(path(d,el.dataset.metric)));
  document.querySelectorAll('[data-note]').forEach(el=>el.textContent=el.dataset.note==='gpu'||el.dataset.note==='temperature'?(d.gpu?'NVIDIA':'NO SENSOR'):'WINDOWS');
  const subtitles={'cpu.usage':d.cpu.clock?`${format(d.cpu.clock/1000,2)} GHz · ${d.system.logical_cores} logical processors`:'Live processor utilization','gpu.usage':d.gpu?d.gpu.name:'NVIDIA sensor unavailable','memory.percent':`${gb(d.memory.used)} / ${gb(d.memory.total)} GB in use`,'gpu.temperature':d.gpu?'Sensor source: NVIDIA':'Detailed sensors not connected'};
  document.querySelectorAll('[data-sub]').forEach(el=>el.textContent=subtitles[el.dataset.sub]);
  document.querySelectorAll('[data-detail]').forEach(el=>el.textContent=display(el.dataset.detail,path(d,el.dataset.detail)));
  const resources={memory:[d.memory.percent,`${gb(d.memory.used)} / ${gb(d.memory.total)} GB`,`${gb(d.memory.total-d.memory.used)} GB available`],gpu:[d.gpu?.memory_total?100*d.gpu.memory_used/d.gpu.memory_total:0,d.gpu?`${format(d.gpu.memory_used/1024,1)} / ${format(d.gpu.memory_total/1024,1)} GB`:'Unavailable','Dedicated graphics memory'],storage:[d.storage.drives[0]?.percent??0,d.storage.drives[0]?`${gb(d.storage.drives[0].used)} / ${gb(d.storage.drives[0].total)} GB`:'Unavailable',d.storage.drives[0]?`${gb(d.storage.drives[0].free)} GB free`:'No drive reported']};
  document.querySelectorAll('[data-resource]').forEach(el=>el.textContent=resources[el.dataset.resource][1]);document.querySelectorAll('[data-bar]').forEach(el=>el.style.width=`${Math.min(100,resources[el.dataset.bar][0])}%`);document.querySelectorAll('[data-resource-note]').forEach(el=>el.textContent=resources[el.dataset.resourceNote][2]);
  document.querySelectorAll('[data-battery]').forEach(el=>el.textContent=d.battery?`${format(d.battery.percent)}% battery · ${d.battery.charging?'AC connected':'On battery'}`:'No battery reported');
  if($('#cores'))$('#cores').innerHTML=d.cpu.cores.map((v,i)=>`<div class="core"><small>CPU ${i+1}</small>${format(v)}%</div>`).join('');
  if($('#drives'))$('#drives').innerHTML=d.storage.drives.map(drive=>`<div class="detail-row"><span>${escapeHtml(drive.name)}</span><strong>${gb(drive.free)} GB free</strong></div>`).join('');
  if($('#addresses'))$('#addresses').innerHTML=d.network.addresses.map(a=>`<div class="detail-row"><span>${escapeHtml(a.adapter)}</span><strong>${escapeHtml(a.ip)}</strong></div>`).join('');
  charts();
}
async function refreshHistory(){const range=state.range;try{const body=await api(`/api/history?seconds=${range}`);if(range!==state.range)return;const byTime=new Map([...body.samples,...state.history].map(s=>[s.timestamp,s]));state.history=[...byTime.values()].sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)).slice(-3600);charts()}catch(e){if(state.paired)toast(e.message)}}
async function refreshApps(){try{state.apps=await api('/api/apps');if(!document.querySelector('[data-app]')&&(state.page==='home'||state.page==='apps'))render();else document.querySelectorAll('[data-app]').forEach(el=>{const app=state.apps.find(a=>a.id===el.dataset.app);if(!app)return;el.disabled=!app.available;const label=el.querySelector('.app-status');label.textContent=appStatus(app);label.classList.toggle('running',app.running&&app.kind!=='website')})}catch(e){if(state.paired)toast(e.message)}}
function connect(){
  clearTimeout(reconnectTimer);if(!state.paired)return;
  const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);state.socket=ws;
  ws.onopen=()=>{state.retry=0;refreshHistory();refreshApps();reportDisplayDetails()};
  ws.onmessage=event=>{const packet=JSON.parse(event.data);if(!packet.data){setConnection(false,'WAITING FOR SENSOR');return}state.data=packet.data;lastSample=Date.parse(packet.data.timestamp);if(state.history.at(-1)?.timestamp!==packet.data.timestamp)state.history.push(packet.data);state.history=state.history.filter(s=>Date.parse(s.timestamp)>Date.now()-3600000).slice(-3600);const fresh=Date.now()-lastSample<=5000;setConnection(fresh,fresh?'LIVE CONNECTION':'READINGS STALE');update()};
  ws.onclose=event=>{if(ws!==state.socket)return;setConnection(false,'RECONNECTING');if(event.code===1008){showPairing();return}if(state.paired)reconnectTimer=setTimeout(connect,Math.min(10000,1000*2**state.retry++)+Math.random()*500)};
  ws.onerror=()=>ws.close();
}
function closeMore(){$('#more-menu').hidden=true;$('#more-toggle').setAttribute('aria-expanded','false')}
function goPage(id){if(!pages[id])return;closeMore();state.page=id;location.hash=id;render();if(id==='games'&&state.paired)refreshGames()}
$('#surface-navigation').addEventListener('click',event=>{const button=event.target.closest('[data-page]');if(button)goPage(button.dataset.page)});
$('#more-toggle').addEventListener('click',()=>{const open=$('#more-menu').hidden;$('#more-menu').hidden=!open;$('#more-toggle').setAttribute('aria-expanded',String(open))});
document.addEventListener('click',event=>{if(!event.target.closest('#surface-navigation'))closeMore()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#more-menu').hidden){closeMore();$('#more-toggle').focus()}});
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(pages[id]&&id!==state.page)goPage(id)});
$('#page-content').addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{
  if(button.dataset.go)goPage(button.dataset.go);
  if(button.hasAttribute('data-screen-focus')){setPresentation(true);try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen()}catch{}return}
  if(button.hasAttribute('data-screen-exit')){setPresentation(false);if(document.fullscreenElement)await document.exitFullscreen();return}
  if(button.hasAttribute('data-screen-awake')){if(wakeStatus==='active')await setKeepAwake(false);else await setKeepAwake(true);return}
  if(button.dataset.clockFormat){screenPreferences.format=button.dataset.clockFormat;saveScreenPreferences();render();return}
  if(button.dataset.sceneSelect){screenPreferences.scene=button.dataset.sceneSelect;saveScreenPreferences();updateAmbient();return}
  if(button.hasAttribute('data-motion-toggle')){screenPreferences.motion=!screenPreferences.motion;saveScreenPreferences();updateAmbient();return}
  if(button.dataset.app){button.disabled=true;try{const result=await api('/api/apps/launch',{method:'POST',body:JSON.stringify({id:button.dataset.app})});toast(result.message);setTimeout(refreshApps,1500)}finally{button.disabled=false}}
  if(button.dataset.media){const result=await api(`/api/media/${button.dataset.media}`,{method:'POST'});toast(result.message)}
  if(button.dataset.range){state.range=Number(button.dataset.range);render();await refreshHistory()}
  if(button.id==='disconnect'){await api('/api/logout',{method:'POST'});state.data=null;state.history=[];render();showPairing()}
  if(button.id==='copy-display-details'){await copyDisplayDetails();return}
  if(button.id==='wake-lock'){await setKeepAwake(!keepAwake);return}
  if(button.id==='wake-retry'){await retryScreenAwake();return}
}catch(e){toast(e.message)}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.paired&&state.socket?.readyState!==WebSocket.OPEN)connect()});
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('Fullscreen is unavailable in this browser.')}});
$('#pair-dialog').addEventListener('cancel',e=>e.preventDefault());
$('#pair-form').addEventListener('submit',async event=>{event.preventDefault();const button=$('#pair-form button');button.disabled=true;$('#pair-error').textContent='';try{const local=state.auth?.local;const result=await api(local?'/api/pair':'/api/device/request',{method:'POST',body:JSON.stringify(local?{code:$('#pair-code').value.trim().toUpperCase(),name:$('#device-name').value.trim()}:{name:$('#device-name').value.trim()})});$('#pair-code').value='';if(result.device.status==='approved')await enterDashboard();else{state.auth.device=result.device;loadPairingMode()}}catch(e){$('#pair-error').textContent=e.message}finally{button.disabled=false}});
let swipeStart;
$('#page-content').addEventListener('touchstart',e=>{swipeStart=null;if(e.target.closest('button,input,select,.games-grid'))return;swipeStart=[e.changedTouches[0].clientX,e.changedTouches[0].clientY]},{passive:true});
$('#page-content').addEventListener('touchend',e=>{if(!swipeStart)return;const dx=e.changedTouches[0].clientX-swipeStart[0],dy=e.changedTouches[0].clientY-swipeStart[1];swipeStart=null;if(Math.abs(dx)>120&&Math.abs(dy)<60){const ids=Object.keys(pages);state.page=ids[(ids.indexOf(state.page)+(dx<0?1:-1)+ids.length)%ids.length];location.hash=state.page;render()}},{passive:true});
setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false});if(lastSample&&Date.now()-lastSample>5000&&state.paired)setConnection(false,'READINGS STALE')},1000);
setInterval(()=>{if(state.paired&&document.visibilityState==='visible')refreshApps()},15000);
let approvalTimer;
async function authStatus(){const response=await fetch('/api/auth');const auth=await response.json();if(!response.ok)throw new Error(auth.detail||'Connection unavailable.');state.auth=auth;return auth}
async function enterDashboard(){clearTimeout(approvalTimer);await api('/api/device/activate',{method:'POST'});await authStatus();$('#pair-dialog').close();state.paired=true;syncScreenAwake();await refreshApps();render();connect();if(state.page==='games')refreshGames()}
async function loadPairingMode(){
  clearTimeout(approvalTimer);
  try{
    const auth=await authStatus();
    const pending=auth.device?.status==='pending';
    $('#setup-code').hidden=!auth.local;
    $('#pair-code').required=auth.local;
    $('#device-name').value=$('#device-name').value||(auth.local?'Dell G16 browser':'Redmi Pad Pro');
    $('#device-name').disabled=pending;
    const button=$('#pair-form button');
    button.hidden=pending;
    button.firstChild.textContent=auth.local?'Set up this laptop ':'Request approval ';
    $('#pair-title').textContent=pending?'Waiting for your laptop.':auth.local?'Set up laptop access.':'Approve this browser.';
    $('#pair-description').textContent=pending?`On your laptop, open Device access from More. Approve “${auth.device.name}” only if its fingerprint matches ${auth.device.fingerprint}. This request expires in 10 minutes.`:auth.local?'Enter the setup code from G16 Command Center.txt on Desktop or in Downloads. This browser will be remembered.':'Name this browser and request approval. Your laptop must approve it before any readings or controls are available.';
    if(pending)approvalTimer=setTimeout(pollApproval,2000);
  }catch(e){$('#pair-error').textContent=e.message}
}
async function pollApproval(){try{const auth=await authStatus();if(auth.device?.status==='approved'){await enterDashboard();return}if(auth.device?.status!=='pending'){await loadPairingMode();$('#pair-error').textContent='The request expired or was rejected. You can request approval again.';return}approvalTimer=setTimeout(pollApproval,2000)}catch{approvalTimer=setTimeout(pollApproval,4000)}}
async function renderDevices(){if($('#approved-devices'))$('#approved-devices').remove();const panel=document.createElement('article');panel.className='card';panel.id='approved-devices';panel.innerHTML='<h2 class="section-title">Approved devices</h2><div class="device-list"></div>';$('#page-content').append(panel);const list=panel.querySelector('.device-list');if(!state.auth?.owner){list.textContent='Manage approved browsers on the laptop at https://localhost:18761. This browser is remembered for up to 180 days, unless you revoke it or clear its cookies.';return}try{const devices=await api('/api/devices');list.innerHTML=devices.map(d=>`<div class="device-entry"><strong>${escapeHtml(d.name)}${d.id===state.auth.device.id?' · this browser':''}</strong><p>${escapeHtml(d.status.toUpperCase())} · Fingerprint ${escapeHtml(d.fingerprint)} · ${escapeHtml(d.address)}${d.display?`<br>${escapeHtml(displayReportSummary(d.display))}`:""}<br>Added ${escapeHtml(new Date(d.created*1000).toLocaleString())}</p>${d.status==='pending'?`<button data-approve="${d.id}">Approve</button><button data-revoke="${d.id}">Reject</button>`:d.status==='approved'?`<button data-revoke="${d.id}">Revoke access</button>`:''}</div>`).join('')||'No devices yet.';const note=document.createElement('p');note.className='device-warning';note.textContent='For a new request, match the fingerprint displayed on the device before approving. Devices are remembered by this browser’s private cookie.';panel.append(note)}catch(e){list.textContent=e.message}}
$('#page-content').addEventListener('click',async event=>{const button=event.target.closest('[data-approve],[data-revoke]');if(!button)return;const id=button.dataset.approve||button.dataset.revoke;const action=button.dataset.approve?'approve':'revoke';button.disabled=true;try{await api(`/api/devices/${id}/${action}`,{method:'POST'});toast(action==='approve'?'Browser approved.':'Browser access revoked.');if(id===state.auth?.device?.id){showPairing();return}await renderDevices()}catch(e){toast(e.message)}finally{button.disabled=false}});
setInterval(()=>{if(['system','devices'].includes(state.page)&&state.auth?.owner&&state.paired&&document.visibilityState==='visible')renderDevices()},5000);
async function init(){if(pages[location.hash.slice(1)])state.page=location.hash.slice(1);render();try{const auth=await authStatus();if(auth.device?.status!=='approved'){showPairing();return}await enterDashboard()}catch{showPairing()}}
init();
