// Private generated files. HTML runs only in an opaque sandbox; PDF pages render locally.
let artifactSelection=null,artifactEpoch=0,artifactRows=[],artifactPdf=null,artifactPdfTask=null,artifactPage=1,artifactGuardTimer=null,artifactWasLocked=false;
function resetArtifacts(clearSelection=true){artifactEpoch++;clearTimeout(artifactGuardTimer);const task=artifactPdfTask||artifactPdf;task?.destroy()?.catch(()=>{});artifactPdfTask=null;artifactPdf=null;artifactRows=[];if(clearSelection){artifactSelection=null;artifactWasLocked=false}document.querySelector('#artifact-preview')?.replaceChildren();document.querySelector('#artifact-select')?.replaceChildren()}
function artifactsFromAction(action){const items=[...(action?.artifacts||[]),...(action?.artifact?[action.artifact]:[]),...(action?.actions||[]).flatMap(item=>item.artifact?[item.artifact]:[])];return [...new Map(items.filter(item=>/^[0-9a-f]{24}$/.test(item?.id)).map(item=>[item.id,item])).values()]}
function artifactLinks(action){return artifactsFromAction(action).map(item=>`<div class="chat-artifact"><button data-artifact="${item.id}">Open ${escapeHtml(item.title||'artifact')}</button><a href="/api/artifacts/${item.id}/download" data-artifact-download="${item.id}" download>Download ${escapeHtml(item.format||'file')}</a></div>`).join('')}
function artifactScreen(){return `<section class="artifact-surface"><div class="artifact-toolbar"><label for="artifact-select">Saved artifacts</label><select id="artifact-select"><option>No artifacts yet</option></select><a id="artifact-download" hidden download>Download</a>${state.auth?.owner?'<button id="artifact-delete" hidden>Delete artifact</button>':''}<button data-go="chat">Ask Jarvis to create one</button></div><p id="artifact-status" role="status">Loading your artifacts…</p><div id="artifact-preview" class="artifact-preview"></div><div id="artifact-paging" hidden><button id="artifact-previous">Previous page</button><span id="artifact-page"></span><button id="artifact-next">Next page</button></div></section>`}
function artifactVisible(epoch){return epoch===artifactEpoch&&state.paired&&state.page==='artifacts'&&document.visibilityState==='visible'&&!!document.querySelector('#artifact-preview')}
async function paintArtifactPdf(epoch){
  const doc=artifactPdf,pageNumber=artifactPage;if(!doc||!artifactVisible(epoch))return;
  const page=await doc.getPage(pageNumber);if(!artifactVisible(epoch)||pageNumber!==artifactPage)return;
  const root=document.querySelector('#artifact-preview'),width=Math.max(240,Math.min(900,root.clientWidth-16)),natural=page.getViewport({scale:1}),scale=width/natural.width;
  const canvas=document.createElement('canvas'),ratio=Math.min(2,window.devicePixelRatio||1),viewport=page.getViewport({scale:scale*ratio});
  canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);canvas.style.width=width+'px';canvas.style.height=Math.ceil(viewport.height/ratio)+'px';canvas.setAttribute('aria-label',`PDF page ${artifactPage} of ${doc.numPages}`);
  await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;if(!artifactVisible(epoch)||pageNumber!==artifactPage)return;
  root.replaceChildren(canvas);document.querySelector('#artifact-page').textContent=`${artifactPage} / ${doc.numPages}`;document.querySelector('#artifact-paging').hidden=doc.numPages<2;document.querySelector('#artifact-previous').disabled=artifactPage<=1;document.querySelector('#artifact-next').disabled=artifactPage>=doc.numPages;
  document.querySelector('#artifact-status').textContent='PDF preview · rendered on this device';
}
async function openArtifactView(identity){
  if(!/^[0-9a-f]{24}$/.test(identity))return;
  resetArtifacts(false);artifactSelection=identity;const epoch=artifactEpoch;
  const select=document.querySelector('#artifact-select');select.innerHTML=artifactRows.map(row=>`<option value="${row.id}">${escapeHtml(row.title)} · ${escapeHtml(row.format.toUpperCase())}</option>`).join('');
  // The caller restores metadata after reset; obtain fresh bounded metadata for this selection.
  try{
    artifactRows=await api('/api/artifacts');if(!artifactVisible(epoch))return;select.innerHTML=artifactRows.map(row=>`<option value="${row.id}">${escapeHtml(row.title)} · ${escapeHtml(row.format.toUpperCase())}</option>`).join('');select.value=identity;
    const item=artifactRows.find(row=>row.id===identity);if(!item)throw new Error('Artifact was removed or is no longer available.');
    const link=document.querySelector('#artifact-download');link.href=`/api/artifacts/${identity}/download`;link.dataset.artifactDownload=identity;link.hidden=false;document.querySelector('#artifact-delete')&&(document.querySelector('#artifact-delete').hidden=false);document.querySelector('#artifact-status').textContent='Opening '+item.title+'…';document.querySelector('#artifact-paging').hidden=true;
    if(item.format==='pdf'){
      const response=await fetch(`/api/artifacts/${identity}/preview`,{cache:'no-store'});if(!response.ok)throw new Error('PDF unavailable. Unlock the PC and try again.');const data=await response.arrayBuffer();if(!artifactVisible(epoch))return;
      const pdfjs=await import('/static/vendor/pdfjs/pdf.min.mjs');if(!artifactVisible(epoch))return;pdfjs.GlobalWorkerOptions.workerSrc='/static/vendor/pdfjs/pdf.worker.min.mjs';
      artifactPdfTask=pdfjs.getDocument({data:new Uint8Array(data),isEvalSupported:false,enableXfa:false,disableAutoFetch:true});const doc=await artifactPdfTask.promise;if(!artifactVisible(epoch)){doc.destroy();return}if(doc.numPages>30){doc.destroy();throw new Error('PDF preview exceeds thirty pages.');}artifactPdf=doc;artifactPage=1;await paintArtifactPdf(epoch);
    }else{
      const frame=document.createElement('iframe');frame.title=item.title;frame.setAttribute('sandbox',item.format==='html'?'allow-scripts':'');frame.referrerPolicy='no-referrer';frame.src=`/api/artifacts/${identity}/preview`;document.querySelector('#artifact-preview').replaceChildren(frame);document.querySelector('#artifact-status').textContent=item.format==='html'?'Interactive HTML preview · isolated from your dashboard':'Source preview · download to keep this file';
    }
  }catch(error){if(artifactVisible(epoch)){document.querySelector('#artifact-status').textContent=error.message;document.querySelector('#artifact-preview').replaceChildren();}}
  if(artifactVisible(epoch))artifactGuardTimer=setTimeout(guardArtifacts,1000);
}
async function guardArtifacts(){const epoch=artifactEpoch;if(!artifactVisible(epoch))return;try{const status=await api('/api/chat/status');if(!artifactVisible(epoch))return;if(status.locked){resetArtifacts(false);artifactWasLocked=true;document.querySelector('#artifact-status').textContent='Unlock the PC to view artifacts.';document.querySelector('#artifact-download').hidden=true;document.querySelector('#artifact-delete')&&(document.querySelector('#artifact-delete').hidden=true)}else if(artifactWasLocked){artifactWasLocked=false;render();return}}catch(error){if(artifactVisible(epoch)){resetArtifacts(false);document.querySelector('#artifact-status').textContent=error.message}}if(state.paired&&state.page==='artifacts'&&document.visibilityState==='visible')artifactGuardTimer=setTimeout(guardArtifacts,1000)}
async function mountArtifacts(){
  if(state.page!=='artifacts'||!state.paired||document.visibilityState!=='visible'||!document.querySelector('#artifact-preview')){resetArtifacts();return}resetArtifacts(false);const epoch=artifactEpoch;
  document.querySelector('#artifact-select').addEventListener('change',event=>openArtifactView(event.target.value));
  for(const [id,delta] of [['artifact-previous',-1],['artifact-next',1]])document.querySelector('#'+id).addEventListener('click',()=>{if(!artifactPdf)return;artifactPage=Math.max(1,Math.min(artifactPdf.numPages,artifactPage+delta));paintArtifactPdf(artifactEpoch).catch(()=>{})});
  document.querySelector('#artifact-delete')?.addEventListener('click',async event=>{const button=event.currentTarget,current=artifactEpoch;if(button.dataset.confirm!=='yes'){button.dataset.confirm='yes';button.textContent='Confirm deletion';return}try{await api('/api/artifacts/'+artifactSelection,{method:'DELETE'});if(artifactVisible(current)){artifactSelection=null;render();}}catch(error){if(state.page==='artifacts')document.querySelector('#artifact-status').textContent=error.message}});
  try{artifactRows=await api('/api/artifacts');if(!artifactVisible(epoch))return;if(!artifactRows.length){document.querySelector('#artifact-status').textContent='Ask Jarvis to build an HTML page, PDF or another supported file.';return}openArtifactView(artifactSelection||artifactRows[0].id)}catch(error){if(artifactVisible(epoch))document.querySelector('#artifact-status').textContent=error.message}
}
document.addEventListener('click',event=>{const button=event.target.closest('[data-artifact]');if(button&&/^[0-9a-f]{24}$/.test(button.dataset.artifact)){artifactSelection=button.dataset.artifact;goPage('artifacts')}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible')resetArtifacts();else if(state.page==='artifacts'&&state.paired)render()});
let artifactResizeTimer=null;window.addEventListener('resize',()=>{clearTimeout(artifactResizeTimer);artifactResizeTimer=setTimeout(()=>{if(artifactPdf&&state.page==='artifacts')paintArtifactPdf(artifactEpoch).catch(()=>{})},150)});

document.addEventListener('click',async event=>{const link=event.target.closest('[data-artifact-download]');if(!link)return;event.preventDefault();const id=link.dataset.artifactDownload;if(!state.paired||!(/^[0-9a-f]{24}$/.test(id)))return;try{const response=await fetch('/api/artifacts/'+id+'/download',{cache:'no-store'});if(response.status===401){showPairing();return}if(!response.ok)throw new Error('Artifact download unavailable. Unlock the PC and try again.');const blob=await response.blob();if(!state.paired||blob.size>256000)throw new Error('Artifact download unavailable.');const disposition=response.headers.get('Content-Disposition')||'',match=disposition.match(/filename="([a-zA-Z0-9_-]{1,60}\.(?:pdf|html|js|css|md|txt|csv|json))"/),download=document.createElement('a'),url=URL.createObjectURL(blob);download.href=url;download.download=match?match[1]:'artifact';document.body.append(download);download.click();download.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){toast(error.message)}});
