// One private, shared Jarvis conversation. Message text is never stored in the browser.
let chatEpoch=0,chatTimer=null,chatRows=[],chatTurn=null,chatSending=false,chatOlder=false,chatPendingText='',chatExpanded=false;
function resetChat(){chatEpoch++;clearTimeout(chatTimer);chatRows=[];chatTurn=null;chatSending=false;chatPendingText='';chatExpanded=false;document.querySelector('#chat-thread')?.replaceChildren();document.querySelector('#chat-input')&&(document.querySelector('#chat-input').value='')}
function chatScreen(){return `<section class="chat-surface"><div class="chat-heading"><span class="surface-overline">ONE CONVERSATION</span><p>Speak or type. Jarvis remembers the conversation either way.</p><button data-go="voice">Voice settings</button>${state.auth?.owner?'<button id="chat-clear">Clear conversation</button>':''}</div><button id="chat-older" hidden>Earlier messages</button><div id="chat-thread" class="chat-thread" role="log" aria-label="Conversation with Jarvis" aria-live="polite"></div><p id="chat-status" role="status">Connecting to Jarvis…</p><form id="chat-form" class="chat-composer"><label for="chat-input" class="chat-input-label">Message Jarvis</label><textarea id="chat-input" maxlength="1000" rows="2" placeholder="Ask Jarvis anything…" autocomplete="off" spellcheck="true"></textarea><div class="chat-composer-actions"><small>Enter to send · Shift + Enter for a new line</small><button id="chat-stop" type="button" hidden>Stop</button><button id="chat-send" type="submit" class="primary" disabled>Send →</button></div></form></section>`}
function chatVisible(epoch){return epoch===chatEpoch&&state.paired&&state.page==='chat'&&document.visibilityState==='visible'&&!!document.querySelector('#chat-form')}
function chatSource(source){try{const url=new URL(source.url);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)return '';return `<a href="${escapeHtml(url.href)}" target="_blank" rel="noopener noreferrer">${escapeHtml(source.title||url.hostname)}</a>`}catch{return ''}}
function paintChat(){
  const thread=document.querySelector('#chat-thread');if(!thread)return;
  const nearBottom=thread.scrollHeight-thread.scrollTop-thread.clientHeight<100;
  thread.innerHTML=chatRows.map(row=>`<article class="chat-exchange" data-chat-row="${Number(row.id)}"><div class="chat-user"><span>You</span><p>${escapeHtml(row.heard)}</p></div><div class="chat-jarvis"><span>Jarvis</span><p>${escapeHtml(row.reply)}</p>${row.action?.message?`<small>${escapeHtml(row.action.message)}</small>`:''}${row.sources?.length?`<div class="chat-sources" aria-label="Sources">${row.sources.map(chatSource).join('')}</div>`:''}</div></article>`).join('')+(chatPendingText?`<div class="chat-user"><span>You</span><p>${escapeHtml(chatPendingText)}</p></div>`:'')||'<div class="chat-welcome"><h2>At your service, sir.</h2><p>Your voice and typed messages appear here together.</p><div class="page-actions"><button data-chat-prompt="What is on my calendar today?">My day</button><button data-chat-prompt="How is my PC doing?">Check my PC</button><button data-chat-prompt="What can you help me with?">What can you do?</button></div></div>';
  if(nearBottom||chatPendingText)thread.scrollTop=thread.scrollHeight;
  document.querySelector('#chat-older').hidden=!chatOlder;
}
async function chatHistory(epoch,older=false){const rows=await api('/api/chat/history'+(older&&chatRows.length?'?before='+chatRows[0].id:''));if(!chatVisible(epoch))return;const previous=JSON.stringify(chatRows);if(older){chatExpanded=true;chatOlder=rows.length===50;chatRows=[...rows,...chatRows]}else if(chatExpanded&&rows.length){chatRows=[...new Map([...chatRows,...rows].map(row=>[row.id,row])).values()].sort((a,b)=>a.id-b.id).slice(-500)}else{chatOlder=rows.length===50;chatRows=rows}if(previous!==JSON.stringify(chatRows)||!document.querySelector('#chat-thread').hasChildNodes())paintChat()}
function chatNavigate(status){const nav=status.turn?.navigation;if(!nav||restState?.rest||state.stale||state.socket?.readyState!==WebSocket.OPEN||document.querySelector('dialog[open]'))return;if(!Number.isFinite(nav.expiresAt)||!Number.isFinite(status.serverTime)||nav.expiresAt<=status.serverTime||nav.expiresAt-status.serverTime>10000)return;let target=nav.screen;if(!Object.hasOwn(pages,target)&&!['weather','f1','focus'].includes(target))return;if(nav.scene!==undefined&&(target!=='ambient'||!Object.hasOwn(ambientScenes,nav.scene)))return;setPresentation(false);if(target==='ambient'&&nav.scene!==undefined){screenPreferences.scene=nav.scene;saveScreenPreferences()}if(['weather','f1'].includes(target)){if(!widgetPreferences[target]||(target==='weather'&&!widgetPreferences.location)){goPage('system');return}widgetPreferences.view=target;saveWidgetPreferences();target='widgets'}if(target==='focus'){focusView=true;target='clock'}else if(target==='clock')focusView=false;goPage(target)}
async function pollChat(epoch){
  if(!chatVisible(epoch))return;
  try{
    const status=await api('/api/chat/status');if(!chatVisible(epoch))return;const spokenBusy=voiceState&&!(['off','listening','followup','error'].includes(voiceState.phase));
    if(status.locked){chatRows=[];chatPendingText='';paintChat();document.querySelector('#chat-status').textContent='Unlock the PC to continue the conversation.'}
    else{await chatHistory(epoch);if(!chatVisible(epoch))return;document.querySelector('#chat-status').textContent=status.busy?'Jarvis is working…':spokenBusy?'Jarvis is handling a spoken request…':!status.enabled?'Enable Personal assistant on the PC to chat.':!status.ready?'Configure the OpenAI key and Jarvis dependencies on the PC.':status.turn?.message||'Ready. The microphone can stay off.';}
    document.querySelector('#chat-send').disabled=chatSending||status.busy||spokenBusy||!status.ready;
    document.querySelector('#chat-stop').hidden=!status.busy;
    document.querySelector('#chat-stop').dataset.turn=status.turn?.id||'';
    if(chatTurn&&status.turn?.id===chatTurn&&status.turn.phase!=='thinking'){
      const completed=status.turn.phase==='done';chatTurn=null;chatPendingText='';paintChat();if(completed)chatNavigate(status);
    }
  }catch(error){if(chatVisible(epoch)){document.querySelector('#chat-status').textContent=error.message;document.querySelector('#chat-send').disabled=true;}}
  if(chatVisible(epoch))chatTimer=setTimeout(()=>pollChat(epoch),1000);
}
function mountChat(){
  resetChat();if(state.page!=='chat'||!state.paired||document.visibilityState!=='visible'||!document.querySelector('#chat-form'))return;
  const epoch=chatEpoch,form=document.querySelector('#chat-form'),input=document.querySelector('#chat-input');
  form.addEventListener('submit',async event=>{event.preventDefault();const text=input.value.trim();if(!text||chatSending||document.querySelector('#chat-send').disabled)return;chatSending=true;document.querySelector('#chat-send').disabled=true;try{const turn=await api('/api/chat/messages',{method:'POST',body:JSON.stringify({text})});if(!chatVisible(epoch))return;chatTurn=turn.id;chatPendingText=text;input.value='';paintChat();document.querySelector('#chat-status').textContent='Jarvis is working…';}catch(error){if(chatVisible(epoch)){document.querySelector('#chat-status').textContent=error.message;toast(error.message)}}finally{chatSending=false;if(chatVisible(epoch)){clearTimeout(chatTimer);pollChat(epoch)}}});
  input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();form.requestSubmit()}});
  document.querySelector('#chat-stop').addEventListener('click',async event=>{const id=event.currentTarget.dataset.turn;if(!id)return;try{await api('/api/chat/stop',{method:'POST',body:JSON.stringify({id})})}catch(error){if(chatVisible(epoch))document.querySelector('#chat-status').textContent=error.message}});
  document.querySelector('#chat-thread').addEventListener('click',event=>{const button=event.target.closest('[data-chat-prompt]');if(button){input.value=button.dataset.chatPrompt;input.focus()}});
  document.querySelector('#chat-older').addEventListener('click',async()=>{try{await chatHistory(epoch,true)}catch(error){if(chatVisible(epoch))document.querySelector('#chat-status').textContent=error.message}});
  document.querySelector('#chat-clear')?.addEventListener('click',async event=>{const button=event.currentTarget;if(button.dataset.confirm!=='yes'){button.dataset.confirm='yes';button.textContent='Confirm clear voice + chat history';return}try{await api('/api/chat/history',{method:'DELETE'});if(chatVisible(epoch)){chatRows=[];chatPendingText='';paintChat();button.dataset.confirm='';button.textContent='Clear conversation';}}catch(error){if(chatVisible(epoch))document.querySelector('#chat-status').textContent=error.message}});
  pollChat(epoch);
}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible')resetChat();else if(state.page==='chat'&&state.paired)mountChat()});
