function gameTiles(){
  const games=state.games.filter(game=>(state.gameFilter==='all'||game.launcher===state.gameFilter)&&game.name.toLowerCase().includes(state.gameSearch.toLowerCase()));
  return games.map(game=>{const initials=game.name.split(/\s+/).filter(word=>!['of','the','and'].includes(word.toLowerCase())).slice(0,2).map(word=>word[0]).join('');const hue=[...game.id].reduce((sum,char)=>sum+char.charCodeAt(0),0)%360;return `<article class="game-card"><div class="game-cover" data-game-hue="${hue}">${game.artwork?`<img src="${escapeHtml(game.artwork)}" alt="" loading="lazy">`:glyph('gaming')}<span class="game-store">${escapeHtml(game.launcher)}</span>${game.artwork?'':`<span class="game-initials">${escapeHtml(initials)}</span>`}</div><div class="game-info"><h3>${escapeHtml(game.name)}</h3><button data-game="${escapeHtml(game.id)}">Play on PC ${glyph('play')}</button></div></article>`}).join('')||'<div class="empty">No games match that selection, sir.</div>';
}
function gamesScreen(){const sources=[...new Set(state.games.map(game=>game.launcher))];return `<div class="library-header"><div><span class="surface-overline">YOUR GAME LIBRARY, SIR</span><h2 class="library-title">Shall we <i>play?</i></h2><p class="game-summary" id="game-summary">${state.gameLibrary?`${state.games.length} games ready for your consideration, sir.`:'Checking your installed games, sir…'}</p></div><button id="refresh-games" aria-label="Refresh game library">Refresh ${glyph('arrow')}</button></div><div class="game-toolbar"><div class="game-filters"><button data-game-filter="all" class="${state.gameFilter==='all'?'active':''}">All</button>${sources.map(source=>`<button data-game-filter="${escapeHtml(source)}" class="${state.gameFilter===source?'active':''}">${escapeHtml(source)}</button>`).join('')}</div><input id="game-search" type="search" value="${escapeHtml(state.gameSearch)}" aria-label="Search installed games" placeholder="Find a game"></div><div id="games-list" class="games-grid">${gameTiles()}</div>${(state.gameLibrary?.warnings||[]).map(message=>`<p class="game-summary">${escapeHtml(message)}</p>`).join('')}`}
function paintGames(){document.querySelectorAll('[data-game-hue]').forEach(el=>el.style.setProperty('--game-color',`hsl(${el.dataset.gameHue} 45% 40%)`))}
let gameRequest=0;
async function refreshGames(force=false){const request=++gameRequest;try{const library=await api(force?'/api/games/refresh':'/api/games',force?{method:'POST'}:{});if(request!==gameRequest)return;state.gameLibrary=library;state.games=library.games;if(state.page==='games'){render();paintGames()}}catch(error){if(state.page==='games'){const summary=document.querySelector('#game-summary');if(summary)summary.textContent='I couldn’t read the game library, sir. Please try Refresh.'}toast(error.message)}}
document.addEventListener('input',event=>{if(event.target.id!=='game-search')return;state.gameSearch=event.target.value;document.querySelector('#games-list').innerHTML=gameTiles();paintGames()});
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button||!(button.dataset.gameFilter||button.dataset.game||button.id==='refresh-games'))return;try{if(button.dataset.gameFilter){state.gameFilter=button.dataset.gameFilter;render();paintGames()}if(button.id==='refresh-games'){button.disabled=true;await refreshGames(true)}if(button.dataset.game){button.disabled=true;const result=await api('/api/games/launch',{method:'POST',body:JSON.stringify({id:button.dataset.game})});toast(result.message)}}catch(error){toast(error.message)}finally{button.disabled=false}});
